// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmwJegWgwP5zPI64SuCV1fNVW0HOI1r3w',
    appId: '1:806262359764:web:710bb43ea78101b7081d41',
    messagingSenderId: '806262359764',
    projectId: 'herbitect-ae294',
    authDomain: 'herbitect-ae294.firebaseapp.com',
    storageBucket: 'herbitect-ae294.appspot.com',
    measurementId: 'G-SR4KV5JS8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG8hRGCsssDf8-jugy-BNm9TOwJxbvC14',
    appId: '1:806262359764:android:006bcffab69de0e9081d41',
    messagingSenderId: '806262359764',
    projectId: 'herbitect-ae294',
    storageBucket: 'herbitect-ae294.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW1bkj0CbzcdjtBc8-bu3_p7HmJJa516s',
    appId: '1:806262359764:ios:8f6f3614b85df30a081d41',
    messagingSenderId: '806262359764',
    projectId: 'herbitect-ae294',
    storageBucket: 'herbitect-ae294.appspot.com',
    iosBundleId: 'com.example.herbitectProtoype1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmwJegWgwP5zPI64SuCV1fNVW0HOI1r3w',
    appId: '1:806262359764:web:5ef4019fc31fff1b081d41',
    messagingSenderId: '806262359764',
    projectId: 'herbitect-ae294',
    authDomain: 'herbitect-ae294.firebaseapp.com',
    storageBucket: 'herbitect-ae294.appspot.com',
    measurementId: 'G-NJ2MGW3CLT',
  );
}
